server:
  port: 8375
  servlet:
    context-path: /gateway
spring:
  application:
    name: VISUAL-GATEWAY
  cloud:
    gateway:
      routes:
        - id: engine
          uri: lb://VISUAL-ENGINE
          predicates:
            - Path=/gateway/engine/**
          filters:
            - StripPrefix=1
        - id: auth
          uri: lb://VISUAL-AUTH
          predicates:
            - Path=/gateway/auth/**
          filters:
            - StripPrefix=1
    discovery:
      enabled: true
eureka:
  client:
    register-with-eureka: true
    registry-fetch-interval-seconds: 10
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

visual:
  gateway:
    white-list:
      pattern:
        - /auth/user/login
        - /auth/user/register
  auth:
    resource-config:
      accessWhiteList:
        - /auth/user/login
        - /auth/user/register
      resourceWhiteList:
        - /auth/user/**
        - /engine/portal/getStatusOptions
        - /engine/portal/getDataSourceOptions
      resources:
        - pattern: /auth/tenant/registerSubTenant
          resource: 注册子账号
        - pattern: /engine/portal/createTemplate
          resource: 发布流程
        - pattern: /engine/portal/getTemplateStr
          resource: 流程模版查看
        - pattern: /engine/portal/changeTemplatePriority
          resource: 修改流程优先级
        - pattern: /engine/portal/changeTemplateRetryCount
          resource: 修改流程失败重试次数
        - pattern: /engine/portal/changeTemplateStatus
          resource: 修改流程模版状态
        - pattern: /engine/portal/getTemplateList
          resource: 查看流程模版列表
        - pattern: /engine/portal/getInstanceList
          resource: 查看流程实例列表
        - pattern: /engine/portal/getLogTimeLine
          resource: 查看实例执行日志
        - pattern: /engine/portal/createInstance
          resource: 运行实例
        - pattern: /engine/portal/terminateInstance
          resource: 终止实例
        - pattern: /engine/portal/getDataSourceList
          resource: 数据源列表
        - pattern: /engine/portal/saveDataSource
          resource: 创建数据源
        - pattern: /engine/portal/deleteDataSource
          resource: 删除数据源
        - pattern: /engine/portal/file/fileManage/mkdir
          resource: 文件管理
        - pattern: /engine/portal/file/fileManage/listDir
          resource: 文件管理
        - pattern: /engine/portal/file/fileManage/download
          resource: 文件管理
        - pattern: /auth/permission/getPermissionList
          resource: 授权管理
        - pattern: /auth/permission/createPermission
          resource: 新建权限
        - pattern: /auth/permission/grantPermission
          resource: 人员赋权
        - pattern: /auth/permission/getGrantViewList
          resource: 赋权人员管理
        - pattern: /auth/permission/retractPermission
          resource: 赋权人员管理
        - pattern: /auth/resource/createResource
          resource: 新建资源
        - pattern: /auth/resource/getResourceList
          resource: 资源管理
        - pattern: /auth/resource/getResourceOption
          resource: 资源管理
        - pattern: /engine/portal/file/fileChunk/**
          resource: 上传文件
    message:
      fetchInterval: 60
    token:
      auth-name: visual
      tenant-name: visual_tenant
      resource-name: visual_resource
      remain-max-count: 10
      activity-timeout: 1800

logging:
  level:
    root:
      error





