server:
  port: 8761
spring:
  application:
    name: eureka
eureka:
  server:
    response-cache-update-interval-ms: 3000
    eviction-interval-timer-in-ms: 3000
  client:
    registerWithEureka: false # 不注册自己
    fetchRegistry: true
  instance:
    prefer-ip-address: true

logging:
  level:
    root:
      error