server:
  port: 8376
  servlet:
    context-path: /auth
spring:
  # sa-token配置
  sa-token:
    # token名称 (同时也是cookie名称)
    token-name: visual
    # token有效期，单位s 默认30天, -1代表永不过期
    timeout: 2592000
    # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
    activity-timeout: 1800
    # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
    allow-concurrent-login: false
    # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
    is-share: false
    # token风格
    token-style: uuid
  application:
    name: VISUAL-AUTH
eureka:
  client:
    register-with-eureka: true
    registry-fetch-interval-seconds: 10
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
visual:
  auth:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/visual_auth?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: tmp
    password: tmp
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



