jasypt:
  encryptor:
    password: visualization
server:
  port: 8374
  servlet:
    context-path: /engine
spring:
  application:
    name: VISUAL-ENGINE
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        ddl-auto: update
        enable_lazy_load_no_trans: true
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: 1ms
    cluster:
      enable: false
eureka:
  client:
    register-with-eureka: true
    registry-fetch-interval-seconds: 10
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true




visual:
  error:
    printStackTrace: true
  db:
    jdbc-url: jdbc:h2:mem:visual;DB_CLOSE_DELAY=-1;CASE_INSENSITIVE_IDENTIFIERS=TRUE;LOCK_MODE=0
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    database-platform: org.hibernate.dialect.H2Dialect
  dag:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/visual_dag?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: tmp
    password: ENC(4SCEneIfzIVS0l85g8AzOWz33Puqe3/gfJo5T9o4x4+1nrtM1olLYZPm8MTHL8Zd)
    stage:
      default-retry-count: 5
      queue-name: visual:pointer:q
      dispatch-batch-size: 20
    worker:
      count: 10
  storage:
    minio:
      enable: true
      endpoint: http://127.0.0.1:9000
      accessKey: akNVhtm8Twid4l0d7Paa
      secretKey: y7d0bWLCTwjJDaV3E3pkmRvR2sepDAKRUxUr1gO3
  log:
    influx:
      connectionString: http://localhost:8086?org=visual&bucket=visual_log&token=Mac63VRKO7Ri-j4ehjJD6pbkkEDbK-Uh8H0RvkIKM81CrDXRPwEm6x93j4E6kM2nF0ajC81WY96fxIASzzJvkQ==
