jasypt:
  encryptor:
    password: visualization
server:
  port: 8374
  servlet:
    context-path: /engine
spring:
  application:
    name: VISUAL-ENGINE
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        ddl-auto: update
        enable_lazy_load_no_trans: true
  redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      lettuce:
        pool:
          min-idle: 0
          max-idle: 8
          max-active: 8
          max-wait: 1ms
      cluster:
        enable: false
eureka:
  client:
    register-with-eureka: true
    registry-fetch-interval-seconds: 10
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true




visual:
  db:
    jdbc-url: jdbc:h2:mem:visual;DB_CLOSE_DELAY=-1;CASE_INSENSITIVE_IDENTIFIERS=TRUE;LOCK_MODE=0
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    database-platform: org.hibernate.dialect.H2Dialect
  dag:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/visual_dag?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: tmp
    password: ENC(4SCEneIfzIVS0l85g8AzOWz33Puqe3/gfJo5T9o4x4+1nrtM1olLYZPm8MTHL8Zd)
    stage:
      defaultRetryCount: 5
    worker:
      count: 10
  storage:
    minio:
      enable: true
      endpoint: http://127.0.0.1:9000
      accessKey: ndF8eqVrmDnzURusQGuo
      secretKey: 6YUXohif1UNYRj5dtnr82ogLnEomewVdjqkuFR3a
#log配置去掉后，默认使用slf4j，只是无法查询执行日志
  log:
    loggerClass: com.visualization.log.logger.TimeSeriesLogService
    influx:
      connectionString : http://localhost:8086?org=visual&bucket=visual_log&token=FqBDSXdY3jYuPbtEe9FeV77cYTWfbUSd7_gxSEq_Sf0VhGr2gqvkd7dEF43w2v8o08ElOVqHk8fJlWUsBzScfg==&
