server:
  port: 8375
  servlet:
    context-path: /gateway
spring:
  application:
    name: VISUAL-GATEWAY
  cloud:
    gateway:
      routes:
        - id: engine
          uri: lb://VISUAL-ENGINE
          predicates:
            - Path=/gateway/engine/**
          filters:
            - StripPrefix=1
    discovery:
      enabled: true
eureka:
  client:
    register-with-eureka: true
    registry-fetch-interval-seconds: 10
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true



